#!/usr/bin/env node
/**
 * WrapBot — Daily learning summary + 60-sec social script
 *
 * Usage:
 *   node wrapbot.js
 *
 * It reads today-notes.txt in this folder (write what you built/learned today),
 * calls Claude, and saves a wrap to personal/wraps/YYYY-MM-DD.md
 *
 * Requires: ANTHROPIC_API_KEY env var
 *   set ANTHROPIC_API_KEY=sk-ant-...
 */

const https = require('https');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const API_KEY = process.env.ANTHROPIC_API_KEY;
const NOTES_FILE = path.join(__dirname, 'today-notes.txt');
const WRAPS_DIR = path.join(__dirname, 'wraps');

if (!API_KEY) {
  console.error('\n❌  ANTHROPIC_API_KEY not set.');
  console.error('    Run: set ANTHROPIC_API_KEY=sk-ant-...\n');
  process.exit(1);
}

function today() {
  return new Date().toISOString().split('T')[0]; // YYYY-MM-DD
}

function callClaude(prompt) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({
      model: 'claude-haiku-4-5',
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }]
    });

    const req = https.request({
      hostname: 'api.anthropic.com',
      path: '/v1/messages',
      method: 'POST',
      headers: {
        'x-api-key': API_KEY,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
        'content-length': Buffer.byteLength(body)
      }
    }, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => {
        try {
          const json = JSON.parse(d);
          if (json.error) return reject(new Error(json.error.message));
          const text = json.content.find(b => b.type === 'text')?.text || '';
          resolve(text);
        } catch(e) { reject(e); }
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

async function getNotes() {
  // Try reading today-notes.txt first
  if (fs.existsSync(NOTES_FILE)) {
    const notes = fs.readFileSync(NOTES_FILE, 'utf8').trim();
    if (notes) {
      console.log('\n📋  Reading today-notes.txt...');
      return notes;
    }
  }

  // Otherwise ask interactively
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => {
    console.log('\n📝  No today-notes.txt found. What did you build/learn today?');
    console.log('    (Type it out, press Enter twice when done)\n');
    let lines = [], lastEmpty = false;
    rl.on('line', line => {
      if (line === '' && lastEmpty) { rl.close(); resolve(lines.join('\n')); }
      else { lines.push(line); lastEmpty = line === ''; }
    });
  });
}

async function run() {
  console.log('\n🤖  WrapBot starting...');

  const notes = await getNotes();
  if (!notes) { console.error('No notes provided. Exiting.'); process.exit(1); }

  console.log('\n⚡  Generating wrap...\n');

  const prompt = `You are WrapBot, a friendly assistant that helps a non-technical entrepreneur named J understand what she built today.

J runs UMEI3D, a 3D-printed footwear brand, and is learning to build her own tech tools and automations. She shares short educational posts on social media about "building in public."

Here are J's notes about what she worked on today:
---
${notes}
---

Generate a daily wrap with TWO sections:

## 🧠 What You Learned Today
Write 3–5 bullet points. Use simple, everyday language — no jargon. Explain what each thing does and WHY it matters for her workflow. Imagine explaining to a smart friend who doesn't code.

## 📱 60-Second Social Script
Write a short, casual spoken script she can record as a video. Format:
- Hook (first 5 seconds — grab attention)
- What she built (15 seconds)
- How it helps her workflow (20 seconds)
- What's next (10 seconds)
- Call to action (5 seconds — "follow for more")

Tone: casual, confident, real — like she's talking to a friend. No corporate speak. No emojis in the script itself. Max 150 words for the script.

Keep everything grounded in her actual work — no fluff.`;

  const result = await callClaude(prompt);

  const date = today();
  const filename = path.join(WRAPS_DIR, `${date}.md`);

  const fileContent = `# WrapBot — ${date}\n\n_Generated by WrapBot from today-notes.txt_\n\n---\n\n${result}\n\n---\n\n**Original Notes:**\n\n${notes}\n`;

  if (!fs.existsSync(WRAPS_DIR)) fs.mkdirSync(WRAPS_DIR, { recursive: true });
  fs.writeFileSync(filename, fileContent, 'utf8');

  console.log(result);
  console.log(`\n✅  Saved to: personal/wraps/${date}.md\n`);

  // Clear notes file after successful run so it's ready for tomorrow
  if (fs.existsSync(NOTES_FILE)) {
    fs.writeFileSync(NOTES_FILE, '', 'utf8');
    console.log('📋  today-notes.txt cleared for tomorrow.\n');
  }
}

run().catch(e => { console.error('Error:', e.message); process.exit(1); });
